// ezxml, Copyright 2019 by Matthew James Briggs
// This file is auto generated by CMake
#pragma once

// The absolute path to the root of the repository.
#ifndef LY_ROOT
#define LY_ROOT "/Users/mjb/repos/ezxml"
#endif

// The absolute path to the binary output directory.
#ifndef LY_BIN
#define LY_BIN "/Users/mjb/repos/ezxml/cmake-build-debug"
#endif
