version: 2
jobs:
  build:
    docker:
      - image: matthewjamesbriggs/cmake:v001

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Cmake
          command: |
              [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ] && \
              cmake -DEZXML_BUILD_EXAMPLES=on -DEZXML_BUILD_TESTS=on -DEZXML_BUILD_CORE_TESTS=on . || \
              cmake -DEZXML_BUILD_EXAMPLES=on -DEZXML_BUILD_TESTS=on -DEZXML_BUILD_CORE_TESTS=off .
      
      - run:
          name: Build
          command: make

      - run:
          name: Run Examples
          command: ./MxRead && ./MxWrite

      - run:
          name: Test
          command: ./MxTest

      # - store_artifacts:
      #     path: /tmp/coverage/
